# Settings
# Use this file as a set of default settings for your GitHub repository.
# See https://probot.github.io/apps/settings/

# Repository settings.
# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
    # Additional tabs.
    has_issues: true
    has_wiki: false
    has_projects: true

    # Merging defaults.
    # When merging pull requests, you can allow any combination of merge commits, squashing, or rebasing.
    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
    - name: Accessibility
    color: d4c5f9
    - name: Admin Page
    color: 006b75
    - name: Build
    color: ffa260
    - name: DO NOT MERGE
    color: b60205
    - name: Docker
    color: d4c5f9
    - name: Docs
    color: d4c5f9
    - name: Good For Community
    color: d64daf
    - name: Hacktoberfest
    color: 00aadc
    - name: Internationalization
    color: d4c5f9
    - name: Master Issue
    color: 5319e7
    - name: Multisite
    color: d4c5f9
    - name: Performance
    color: d4c5f9
    - name: "[Pri] BLOCKER"
    color: e84d10
    - name: "[Pri] High"
    color: ec9a71
    - name: "[Pri] Low"
    color: fef2c0
    - name: "[Pri] Normal"
    color: fad8c7
    - name: "[Status] Blocked / Hold"
    color: ededed
    - name: "[Status] Bug Scrub"
    color: fbca04
    - name: "[Status] Design Review Complete"
    color: bada55
    - name: "[Status] Has Changelog"
    color: bada55
    - name: "[Status] In Progress"
    color: 207de5
    - name: "[Status] Invalid"
    color: ededed
    - name: "[Status] Needs Author Reply"
    color: e11d21
    - name: "[Status] Needs Changelog"
    color: eb6420
    - name: "[Status] Needs Cherry-Pick"
    color: ed71a7
    - name: "[Status] Needs Copy Review"
    color: f7ec96
    - name: "[Status] Needs Copy"
    color: eeffa3
    - name: "[Status] Needs Design Review"
    color: c0ffee
    - name: "[Status] Needs Design"
    color: f7838e
    - name: "[Status] Needs GDPR Review"
    color: ededed
    - name: "[Status] Needs Product Review"
    color: 96dcec
    - name: "[Status] Needs Review"
    color: fbca04
    - name: "[Status] Needs Testing"
    color: fbca04
    - name: "[Status] Needs Unit Tests"
    color: f24f90
    - name: "[Status] Proposal"
    color: FC2888
    - name: "[Status] Ready to Merge"
    color: 009800
    - name: "[Status] Stale"
    color: ededed
    - name: "[Status] Tested on WP.com"
    color: 009800
    - name: "[Status] Wontfix"
    color: 000000
    - name: "[Type] Bug"
    color: fc2929
    - name: "[Type] Dotcom Merge"
    color: bfdadc
    - name: "[Type] Duplicate"
    color: c7def8
    - name: "[Type] Enhancement"
    color: c7def8
    - name: "[Type] Feature"
    color: c7def8
    - name: "[Type] Good First Bug"
    color: 00aadc
    - name: "[Type] Happiness Request"
    color: d4c5f9
    - name: "[Type] Janitorial"
    color: c7def8
    - name: "[Type] Question"
    color: d4c5f9
    - name: "[Type] Task"
    color: c7def8
    - name: Unit Tests
    color: 006b75
